version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=0s'  # 永久保留數據 (無限期)
      - '--storage.tsdb.allow-overlapping-blocks'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'  # 啟用熱重載配置
    ports:
      - 9090:9090
    restart: always
    user: root  # 確保具有足夠權限寫入數據卷

  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091
    restart: always
    volumes:
      - pushgateway_data:/persistence  # 持久化 Push Gateway 數據
    command:
      - '--persistence.file=/persistence/pushgateway.data'
      - '--persistence.interval=5m'
    
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/prometheus
  
  pushgateway_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/pushgateway
  
  grafana_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/grafana
